services:
  postgres:
    image: "postgres:16"
    container_name: jobhuntinger-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobhuntingerdb
      POSTGRES_USER: jhUser
      POSTGRES_PASSWORD: jhPass
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - jobhuntiger_net

  backend:
    image: "adoumadje/jobhuntinger-backend"
    container_name: jobhuntiger-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      CLIENT_URL: "http://localhost:8180"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobhuntingerdb
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_WEB_FILTERCHAINPROXY: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_WEB_ACCESS_INTERCEPT_REQUESTMATCHERDELEGATINGAUTHORIZATIONMANAGER: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_WEB_HEADER_WRITERS_HSTSHEADERWRITER: INFO
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - jobhuntiger_net

  frontend:
    image: "adoumadje/jobhuntinger-frontend"
    container_name: jobhuntiger-frontend
    ports:
      - "8180:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - jobhuntiger_net

networks:
  jobhuntiger_net:
    driver: bridge