services:
  postgres:
    image: "postgres:16"
    container_name: jobhuntinger-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobhuntingerdb
      POSTGRES_USER: jhUser
      POSTGRES_PASSWORD: jhPass
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - jobhuntiger_net

  backend:
    image: "adoumadje/jobhuntinger-backend"
    container_name: jobhuntiger-backend
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobhuntingerdb
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - jobhuntiger_net

  frontend:
    image: "adoumadje/jobhuntinger-frontend"
    container_name: jobhuntiger-frontend
    ports:
      - "8180:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - jobhuntiger_net

networks:
  jobhuntiger_net:
    driver: bridge