spring:
  application:
    name: jobhuntinger

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:jobhuntingerdb
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
  liquibase:
    enabled: false

  config:
    import:
      - "application-liquibase.yaml"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://accounts.google.com"

logging:
  level:
    org.springframework.security: trace

client:
  url: "http://localhost:4200"