spring:
  config:
    activate:
      on-profile: "prod"

  h2:
    console:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5433/jobhuntingerdb
    username: jhUser
    password: jhPass

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/prod/changelog0.0_master.xml