name: "build backend docker"

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

  workflow_dispatch:

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
          cache-dependency-path: backend/pom.xml

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Build and push image with Jib
        run: |
          ./mvnw compile jib:build \
            -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }} \
            -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }}
